# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OI26MCKJF2AkZLans0O52OuNlmTd_XbC
"""

!pip install pandas selfies torch transformers deepchem rdkit swifter tqdm
!pip install faiss-cpu sentence-transformers pillow

!pip install rank_bm25 openai

"""
多索引RAG系统 - 彻底解决内存问题
策略：构建多个独立的小索引，避免单个索引过大
"""

import json
import pickle
import numpy as np
from pathlib import Path
from typing import List, Dict
import re
import os
import gc

import faiss
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

# ============ 配置 ============
GDRIVE_BASE = "/content/drive/MyDrive"
PROJECT_NAME = "PatentRAG"
GDRIVE_PROJECT = f"{GDRIVE_BASE}/{PROJECT_NAME}"
os.makedirs(GDRIVE_PROJECT, exist_ok=True)

print(f"✓ 项目目录: {GDRIVE_PROJECT}")


# ============ 快速构建单个小索引 ============

def build_small_index(index_id: int, docs_per_index: int = 90):
    """
    构建单个小索引（安全！）

    Args:
        index_id: 索引编号 (0-9)
        docs_per_index: 每个索引包含的文档数
    """

    print(f"\n{'='*80}")
    print(f"🔨 构建索引 {index_id}")
    print(f"{'='*80}")

    # 1. 加载模型
    print("🔄 加载模型...")
    encoder = SentenceTransformer('all-MiniLM-L6-v2')
    dimension = 384

    # 2. 查找文档
    base_path = Path("/content/drive/MyDrive/MinerU")
    all_docs = sorted([f.parent for f in base_path.rglob("full.md")])

    start_idx = index_id * docs_per_index
    end_idx = min(start_idx + docs_per_index, len(all_docs))

    if start_idx >= len(all_docs):
        print(f"⚠️  索引 {index_id} 超出范围")
        return

    my_docs = all_docs[start_idx:end_idx]
    print(f"📝 处理文档 {start_idx+1}-{end_idx} ({len(my_docs)}个)")

    # 3. 创建索引
    index = faiss.IndexFlatIP(dimension)
    documents = []

    # 4. 处理文档
    for doc_dir in tqdm(my_docs, desc=f"索引{index_id}"):
        try:
            # 读取full.md
            full_md = (doc_dir / "full.md").read_text(encoding='utf-8')

            # 简单分块（按段落）
            chunks = [p.strip() for p in full_md.split('\n\n') if len(p.strip()) > 50]

            if not chunks:
                continue

            # 向量化（小批次）
            for i in range(0, len(chunks), 8):
                batch = chunks[i:i+8]
                embeddings = encoder.encode(batch, show_progress_bar=False, convert_to_numpy=True)
                embeddings = embeddings.astype('float32')
                faiss.normalize_L2(embeddings)

                index.add(embeddings)

                # 保存元数据
                for chunk in batch:
                    documents.append({
                        'content': chunk,
                        'metadata': {'doc_id': doc_dir.name, 'title': ''}
                    })
        except Exception as e:
            print(f"\n✗ {doc_dir.name[:30]}: {str(e)[:50]}")

    # 5. 保存这个小索引
    save_path = Path(f"{GDRIVE_PROJECT}/index_{index_id}")
    save_path.mkdir(parents=True, exist_ok=True)

    faiss.write_index(index, str(save_path / "faiss.index"))

    with open(save_path / "documents.pkl", 'wb') as f:
        pickle.dump({'documents': documents, 'dimension': dimension}, f)

    print(f"\n✅ 索引 {index_id} 完成: {len(documents)} 个文档块")
    print(f"💾 保存位置: {save_path}")

    # 清理内存
    del encoder, index, documents
    gc.collect()


# ============ 查询多个索引 ============

def search_all_indices(query: str, top_k: int = 5):
    """搜索所有小索引并合并结果"""

    print(f"🔍 搜索: {query}")

    # 加载模型
    encoder = SentenceTransformer('all-MiniLM-L6-v2')
    query_embedding = encoder.encode(query, convert_to_numpy=True)
    query_embedding = query_embedding.astype('float32').reshape(1, -1)
    faiss.normalize_L2(query_embedding)

    all_results = []

    # 搜索每个索引
    for i in range(10):  # 0-9共10个索引
        index_path = Path(f"{GDRIVE_PROJECT}/index_{i}")

        if not index_path.exists():
            continue

        # 加载索引
        index = faiss.read_index(str(index_path / "faiss.index"))
        with open(index_path / "documents.pkl", 'rb') as f:
            data = pickle.load(f)

        # 搜索
        distances, indices = index.search(query_embedding, top_k)

        for dist, idx in zip(distances[0], indices[0]):
            if idx < len(data['documents']):
                all_results.append({
                    'content': data['documents'][idx]['content'],
                    'metadata': data['documents'][idx]['metadata'],
                    'score': float(dist)
                })

    # 按分数排序
    all_results.sort(key=lambda x: x['score'], reverse=True)

    # 返回Top-K
    return all_results[:top_k]


# ============ 使用示例 ============

# 步骤1: 构建所有小索引（一次一个，避免内存问题）
for i in range(10):
    build_small_index(i, docs_per_index=90)

# 步骤2: 查询
results = search_all_indices("Which photoinitiators work better under LED?", top_k=5)

for i, r in enumerate(results, 1):
    print(f"\n[{i}] 分数: {r['score']:.3f}")
    print(f"内容: {r['content'][:200]}...")

"""
多索引高级RAG系统
功能：多索引 + BM25混合检索 + 重排序 + DeepSeek
"""

import json
import pickle
import numpy as np
from pathlib import Path
from typing import List, Dict
import re

import faiss
from sentence_transformers import SentenceTransformer, CrossEncoder
from rank_bm25 import BM25Okapi
from openai import OpenAI

# ============ 配置 ============
GDRIVE_PROJECT = "/content/drive/MyDrive/PatentRAG"
NUM_INDICES = 10  # 索引数量


class MultiIndexRAG:
    """多索引RAG系统（支持高级功能）"""

    def __init__(self, use_reranker: bool = True, deepseek_api_key: str = None):
        """
        Args:
            use_reranker: 是否使用重排序
            deepseek_api_key: DeepSeek API密钥（可选）
        """
        print("🔄 初始化高级RAG系统...")

        # 向量检索模型
        self.encoder = SentenceTransformer('all-MiniLM-L6-v2')

        # 重排序模型（可选）
        self.reranker = None
        if use_reranker:
            print("🔄 加载重排序模型...")
            self.reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
            print("✓ 重排序模型加载完成")

        # DeepSeek LLM（可选）
        self.llm = None
        if deepseek_api_key:
            self.llm = OpenAI(
                api_key=deepseek_api_key,
                base_url="https://api.deepseek.com"
            )
            print("✓ DeepSeek LLM已初始化")

        # BM25索引（延迟加载）
        self.bm25 = None
        self.bm25_docs = None

        print("✅ 系统初始化完成")

    def search_vector(self, query: str, top_k: int = 20) -> List[Dict]:
        """向量检索（多索引）"""

        # 向量化查询
        query_embedding = self.encoder.encode(query, convert_to_numpy=True)
        query_embedding = query_embedding.astype('float32').reshape(1, -1)
        faiss.normalize_L2(query_embedding)

        all_results = []

        # 搜索所有索引
        for i in range(NUM_INDICES):
            index_path = Path(f"{GDRIVE_PROJECT}/index_{i}")

            if not index_path.exists():
                continue

            # 加载索引
            index = faiss.read_index(str(index_path / "faiss.index"))
            with open(index_path / "documents.pkl", 'rb') as f:
                data = pickle.load(f)

            # 搜索
            distances, indices = index.search(query_embedding, top_k // NUM_INDICES + 5)

            for dist, idx in zip(distances[0], indices[0]):
                if idx < len(data['documents']):
                    all_results.append({
                        'content': data['documents'][idx]['content'],
                        'metadata': data['documents'][idx]['metadata'],
                        'score': float(dist),
                        'source': 'vector'
                    })

        # 按分数排序
        all_results.sort(key=lambda x: x['score'], reverse=True)

        return all_results[:top_k]

    def search_bm25(self, query: str, top_k: int = 20) -> List[Dict]:
        """BM25检索"""

        # 延迟构建BM25索引
        if self.bm25 is None:
            print("🔨 构建BM25索引（首次查询需要）...")
            self._build_bm25_index()

        # 分词
        query_tokens = re.findall(r'\b\w+\b', query.lower())

        # BM25评分
        scores = self.bm25.get_scores(query_tokens)

        # 获取Top-K
        top_indices = np.argsort(scores)[::-1][:top_k]

        results = []
        for idx in top_indices:
            if scores[idx] > 0:
                results.append({
                    'content': self.bm25_docs[idx]['content'],
                    'metadata': self.bm25_docs[idx]['metadata'],
                    'score': float(scores[idx]),
                    'source': 'bm25'
                })

        return results

    def _build_bm25_index(self):
        """构建BM25索引（从所有小索引中加载文档）"""

        all_docs = []
        tokenized_corpus = []

        for i in range(NUM_INDICES):
            index_path = Path(f"{GDRIVE_PROJECT}/index_{i}")
            if not index_path.exists():
                continue

            with open(index_path / "documents.pkl", 'rb') as f:
                data = pickle.load(f)

            for doc in data['documents']:
                all_docs.append(doc)
                tokens = re.findall(r'\b\w+\b', doc['content'].lower())
                tokenized_corpus.append(tokens)

        self.bm25_docs = all_docs
        self.bm25 = BM25Okapi(tokenized_corpus)

        print(f"✓ BM25索引完成: {len(all_docs):,} 个文档")

    def search_hybrid(
        self,
        query: str,
        top_k: int = 10,
        vector_weight: float = 0.7,
        use_rerank: bool = True
    ) -> List[Dict]:
        """
        混合检索（向量 + BM25 + 重排序）

        Args:
            query: 查询文本
            top_k: 返回结果数
            vector_weight: 向量检索权重（0-1）
            use_rerank: 是否使用重排序
        """

        # 1. 向量检索
        vector_results = self.search_vector(query, top_k=top_k * 2)

        # 2. BM25检索
        bm25_results = self.search_bm25(query, top_k=top_k * 2)

        # 3. 融合（归一化分数）
        def normalize_scores(results):
            if not results:
                return []
            scores = [r['score'] for r in results]
            min_s, max_s = min(scores), max(scores)
            range_s = max_s - min_s if max_s > min_s else 1.0

            for r in results:
                r['score'] = (r['score'] - min_s) / range_s
            return results

        vector_results = normalize_scores(vector_results)
        bm25_results = normalize_scores(bm25_results)

        # 合并（加权）
        merged = {}
        bm25_weight = 1.0 - vector_weight

        for r in vector_results:
            key = r['content'][:100]
            merged[key] = {
                'content': r['content'],
                'metadata': r['metadata'],
                'score': r['score'] * vector_weight,
                'source': 'hybrid'
            }

        for r in bm25_results:
            key = r['content'][:100]
            if key in merged:
                merged[key]['score'] += r['score'] * bm25_weight
            else:
                merged[key] = {
                    'content': r['content'],
                    'metadata': r['metadata'],
                    'score': r['score'] * bm25_weight,
                    'source': 'hybrid'
                }

        results = sorted(merged.values(), key=lambda x: x['score'], reverse=True)[:top_k * 2]

        # 4. 重排序（可选）
        if use_rerank and self.reranker is not None:
            pairs = [[query, r['content'][:500]] for r in results]
            rerank_scores = self.reranker.predict(pairs)

            for r, score in zip(results, rerank_scores):
                r['score'] = float(score)
                r['source'] = 'hybrid_reranked'

            results.sort(key=lambda x: x['score'], reverse=True)

        return results[:top_k]

    def query_with_llm(
        self,
        query: str,
        top_k: int = 5,
        use_hybrid: bool = True
    ) -> tuple:
        """
        使用LLM生成答案

        Returns:
            (answer, retrieved_results)
        """

        if self.llm is None:
            raise ValueError("请先设置 deepseek_api_key")

        # 检索
        if use_hybrid:
            results = self.search_hybrid(query, top_k=top_k)
        else:
            results = self.search_vector(query, top_k=top_k)

        # 构建上下文
        context = "\n\n".join([
            f"[文献 {i+1}] 相关度: {r['score']:.3f}\n"
            f"内容: {r['content'][:800]}"
            for i, r in enumerate(results[:5])
        ])

        # 构建Prompt
        prompt = f"""你是一位专业的化学文献分析助手。请基于以下文献片段回答用户的问题。

要求：
1. 直接回答问题，引用具体文献内容
2. 如果文献中没有直接答案，说明相关信息
3. 保持客观和专业

文献片段：
{context}

用户问题：{query}

回答："""

        # 调用DeepSeek
        response = self.llm.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": "你是一位专业的化学文献分析助手。"},
                {"role": "user", "content": prompt}
            ],
            max_tokens=2048,
            temperature=0.7
        )

        answer = response.choices[0].message.content

        return answer, results


# ============ 使用示例 ============

def example_usage():
    """完整使用示例"""

    print("="*80)
    print("🚀 多索引高级RAG系统")
    print("="*80)

    # 1. 初始化（不使用DeepSeek）
    rag = MultiIndexRAG(
        use_reranker=True,
        deepseek_api_key=None  # 暂不使用LLM
    )

    # 2. 测试不同检索策略
    query = "Which photoinitiators work better under LED light sources?"

    print(f"\n{'='*80}")
    print(f"查询: {query}")
    print(f"{'='*80}")

    # 2a. 纯向量检索
    print("\n【策略1】纯向量检索:")
    results = rag.search_vector(query, top_k=3)
    for i, r in enumerate(results, 1):
        print(f"[{i}] {r['score']:.3f} | {r['content'][:100]}...")

    # 2b. 混合检索 + 重排序
    print("\n【策略2】混合检索 + 重排序:")
    results = rag.search_hybrid(query, top_k=3)
    for i, r in enumerate(results, 1):
        print(f"[{i}] {r['score']:.3f} | {r['source']} | {r['content'][:100]}...")

    print("\n✅ 测试完成！")


def query_with_deepseek():
    """使用DeepSeek生成答案"""

    # 初始化（带DeepSeek）
    rag = MultiIndexRAG(
        use_reranker=True,
        deepseek_api_key="sk-xxxxxxxxxxxxx"  # 替换为你的API密钥
    )

    query = "Which photoinitiators work better under LED light sources?"

    # 生成答案
    answer, results = rag.query_with_llm(query, top_k=5, use_hybrid=True)

    print(f"\n💡 DeepSeek回答:")
    print("="*80)
    print(answer)
    print("="*80)

    print(f"\n📚 参考文献:")
    for i, r in enumerate(results, 1):
        print(f"[{i}] {r['score']:.3f} | {r['metadata']['doc_id'][:50]}")


# ============ 运行 ============
if __name__ == "__main__":
    # 先安装依赖
    # !pip install rank-bm25 openai -q

    # 运行示例
    # example_usage()
    query_with_deepseek()

# 📝 完整使用流程（在Colab中）

# # ============================================
# # Cell 1: 安装额外依赖
# # ============================================
# !pip install rank-bm25 openai -q

# # ============================================
# # Cell 2: 运行高级RAG（复制上面完整代码）
# # ============================================
# # （粘贴上面的完整代码）

# # ============================================
# # Cell 3: 测试（不使用DeepSeek）
# # ============================================
  # rag = MultiIndexRAG(use_reranker=True, deepseek_api_key=None)

  # # 混合检索测试
  # results = rag.search_hybrid(
  #     "Which photoinitiators work better under LED?",
  #     top_k=5
  # )

  # for i, r in enumerate(results, 1):
  #     print(f"\n[{i}] 分数: {r['score']:.3f} | 来源: {r['source']}")
  #     print(f"内容: {r['content'][:200]}...")

# # ============================================
# # Cell 4: 使用DeepSeek（可选）
# # ============================================
  # rag = MultiIndexRAG(
  #     use_reranker=True,
  #     deepseek_api_key="sk-xxxxxxxxxx"  # 填入你的API密钥
  # )

  # answer, refs = rag.query_with_llm(
  #     "如何选择适合LED光源的光引发剂？",
  #     top_k=5
  # )

  # print("💡 回答:")
  # print(answer)